### ISSUE TITLE
Feature Request: Annotated tags

### ISSUE THREAD

**Issue by frankdugan3** [lud/mix_version#1]
First, great library!

As I understand it, it seems that it is generally encouraged to use [annotated tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging#_annotated_tags) for tags that are intended to be shared outside the local repo. This enables the use of `push.followTags` setting to automatically push such tags by default.

Would you consider switching to annotated tags, or providing them as a configurable option?

[See this StackOverflow](https://stackoverflow.com/questions/5195859/how-do-you-push-a-tag-to-a-remote-repository-using-git) for more context.

**Comment by lud** [comment]
Hi, Thanks :)

Adding annotations can be done.

I am not sure about how to tackle this though. We could add a `-a` option that takes a message and annotates the tag or pulls a default message from the local config. And another configuration option that would say "always annotate".

I do not really like the fact that a project's config holds configuration for an external tool (as it is not intended to be a dependency) but I do not like global config for such tools. At least it would be totally optional so why not.

What do you think ?

**Comment by frankdugan3** [comment]
I like both the `-a` flag and the config options.

Personally, I include this tool in my `mix.exs` file, but mark it as dev-only and non-runtime, like a lot of folks do with `credo`: `{:mix_version, "~> 1.2", only: :dev, runtime: false}`. From my perspective, that means it's installed and configured for whoever is working on the repo, and I can just document the `mix version -p`, etc. commands in my `README.md` file.

**Comment by lud** [comment]
alright then, I don't know when but I'll do it.

**Comment by lud** [comment]
Hi, 

I just pushed 1.3 to Github, but not to hex.pm yet. Can you please tell me if it works well for you?

I do not have a good testing strategy yet. Because to test for Git I must create a project in a new directory outside of the project, and then let the tests issue git commands and read Git state to see if everything worked as intended. That would take a lot of time for such a tiny project.

**Comment by frankdugan3** [comment]
Looks good to me. Thanks!

**Comment by lud** [comment]
Cool thanks
