### ISSUE TITLE
No annotation even when I specify `annotation: true` in the project config.

### ISSUE THREAD

**Issue by whmountains** [lud/mix_version#2]
Steps to reproduce:

- Enable annotation in mix.exs (or use the default configuration)
- Run the tool with minimal cli flags: `mix version -p`

What seems to be happening is that CLIMate returns `false` instead of `nil` when the annotate option is not specified, which overrides anything specified in the project.

**Comment by lud** [comment]
Hi, 

Thank you for the bug report.

Indeed, CliMate defaults to false when reading boolean options. That was a bad choice, I don't remember why. I'll have to update climate to v3 to remove that.

**Comment by whmountains** [comment]
Great!  Locally I rewrote it to use OptionParser, but climate does have a lot more features in things like automatic printing of usage.  One thing you might consider is changing climate to use OptionParser under the hood for actual parsing of the arguments, while exposing a nicer API.

**Comment by lud** [comment]
CliMate [is using OptionParser](https://github.com/lud/cli_mate/blob/a84aa08453d46acbd0eaee8baa72bc86f3e10513/lib/cli_mate.ex#L375).

I just forced booleans to default to false, for whatever reason. I just removed that. You can use `mix_version 2.2.1` and it should work as intended.

**Comment by whmountains** [comment]
Oh!  Does that mean the negation flags work too?  For example would `--no-anotate` disable annotations when the mix config has `annotate: true`?

**Comment by whmountains** [comment]
I just installed the latest version and it works great.

As an aside, digging through your codebase to find the issue was a pleasure.  Really clean and easy to understand.

Thank you for the the quick fix and excellent tool.

**Comment by lud** [comment]
Yes it would, i tested all `-a`, `--no-annotation` and no option with both `[annotate: true]` and `[annotate: false]`

**Comment by lud** [comment]
Thank you for your kind words!
